### PR TITLE
use prepend

### PR DESCRIPTION
**Pull request by grosser**
was trying to mix this with another prepend and it resulted in a stack level too deep ... so switch to prepend ?

### CODE REVIEW

**Comment by grosser** [comment]
@kratob

**Comment by grosser** [comment]
tried it here and works fine https://github.com/zendesk/samson/pull/1737

**Comment by kratob** [comment]
Makes sense, thanks.

I've released it as 0.6.1.

**Comment by grosser** [comment]
thx! :D

**Pull request merged**
