### PR TITLE
drop super old rails versions and unmaintained ruby versions

### PR DESCRIPTION
**Pull request by grosser**
- configured travis for faster runs
 - test against multiple ruby versions

users stuck on 2.3 / 3.0 / 1.9 etc can always use an older version

@kratob

### CODE REVIEW

**Comment by grosser** [comment]
can you go to https://travis-ci.org/profile and turn on builds for https://travis-ci.org/makandra/query_diet ?

**Comment by grosser** [comment]
- simplified Rakefile
 - make `rake` check || install bundler first so nobody has to read any instructions
 - use `sh` so commands are visible / easy to reproduce / script stops and fails when commands fail
 - hide migration output
 - fix random error in logger_spec (paused being set to nil)

**Comment by grosser** [comment]
@kratob looks good ?

**Comment by kratob** [comment]
I'm a bit torn, to be honest. I appreciate the effort, but we're kind of in the business of supporting ancients Railses, so I'm reluctant to merge this. 

I agree with the changes to the default rake task and the travis integration, but I see no real reason to drop the 2.3 support at this time, other than making testing more convenient.

If you intend to make some other changes and need this as a prerequisite, I'm fine with merging it. But since the gem hasn't substantially changed in years, I don't want to drop 2.3 support just for the sake of it.

**Comment by grosser** [comment]
running 2.3 on ruby 2.0 won't work, so this means adding super old rubies and having their tests fail, so I'd opt for modernizing and kicking out the junk, since anyone stuck on 2.3 or 3.2 does not need a new query_diet version + it will make future work easier.

**Comment by kratob** [comment]
I guess it's indeed unlikely that someone stuck on Rails 2.3 will add query_diet today. I'll merge it.

**Comment by grosser** [comment]
:heart:

**Pull request merged**
